### PR TITLE
Added ability to save picture between reloads + total rewrire

### PR DESCRIPTION
**Pull request by Vampire2008**
If host uses this mod all clients must also install this mod for correct data exchange.

Clients can safely use this mod if host doesn't have it.

### CODE REVIEW

**Comment by Vampire2008** [comment]
@BoniatoRelleno, I tired waiting you.
If you do not show activity until week end (sunday is last day of week for me) I will close this PR and upload my fork as another mod to Thunderstore.

**Comment by BoniatoRelleno** [comment]
Sorry, I wanted to test it thoroughly before publishing it but I do not have much time, I will test it briefly and publish it.

**Comment by BoniatoRelleno** [comment]
I have done a test by opening the game twice in LAN mode, I have taken two paintings and when exiting and re-entering the game the host sees that only one of the paintings has kept the original texture and the client sees the two paintings with different textures

**Comment by Vampire2008** [comment]
I didn't test LAN mode. It seems in LAN mode Lobby storage works differently and client think that host doesn't have mod (it randomly change material of paiting).
On host you picked up in facility paintings or spawed them using dev tools?

**Comment by BoniatoRelleno** [comment]
I picked up the paintings in the facility, I am going to try online now

**Comment by BoniatoRelleno** [comment]
Well, I could not test it in multiplayer but at least online it works playing alone so I will trust that it works

**Pull request merged**
